---

- name: include distribution specific variables
  include_vars:
    dir: vars
    files_matching: "{{ item }}"
  loop:
    - "{{ ansible_facts.system }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution + '_' + ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution + '_' + ansible_facts.distribution_version }}.yml"

- name: include service variables
  include_vars:
    dir: vars
    files_matching: "service.yml"
  when: has_service|d(false)

- name: include daemontools variables
  include_vars:
    dir: vars
    files_matching: "daemontools.yml"
  when: has_daemontools|d(false)

- name: include runit variables
  include_vars:
    dir: vars
    files_matching: "runit.yml"
  when: has_runit|d(false)
