---

- block:

    - name: check current lazygit
      ansible.builtin.stat:
        path: "{{ system_tools_lazygit_local_bin }}"
      register: t_system_tools_lazygit_local_bin

    - block:

        - name: get latest lazygit version from GitHub API
          ansible.builtin.uri:
            url: "{{ system_tools_lazygit_github_api_url }}"
            return_content: yes
          register: t_system_tools_lazygit_github_latest_release
          changed_when: no

        - name: extract latest lazygit version
          ansible.builtin.set_fact:
            system_tools_lazygit_version: "{{ (t_system_tools_lazygit_github_latest_release.content | from_json).tag_name | replace('v', '') }}"

      when: system_tools_lazygit_version is not defined or system_tools_lazygit_version == ""

    - block:

        - name: get current lazygit version
          ansible.builtin.shell:
            cmd: "{{ system_tools_lazygit_local_bin }} --version | sed -e 's/^.*, version=\\([^,]*\\).*/\\1/g'"
          register: t_system_tools_lazygit_current_version
          changed_when: no

      when: t_system_tools_lazygit_local_bin.stat.exists

    - block:

        - name: download lazygit archive
          ansible.builtin.get_url:
            url: "{{ system_tools_lazygit_github_download_url }}"
            dest: "{{ system_tmp_dir }}/lazygit.tar.gz"
            mode: '0644'

        - name: extract lazygit archive
          ansible.builtin.unarchive:
            src: "{{ system_tmp_dir }}/lazygit.tar.gz"
            dest: "{{ system_tmp_dir }}"
            remote_src: yes
            creates: "{{ system_tmp_dir }}/lazygit"

        - name: "install lazygit binary to {{ system_tools_lazygit_local_bin }}"
          ansible.builtin.copy:
            src: "{{ system_tmp_dir }}/lazygit"
            dest: "{{ system_tools_lazygit_local_bin }}"
            mode: '0755'
            owner: root
            group: root
            remote_src: yes

        - name: clean up temporary files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ system_tmp_dir }}/lazygit.tar.gz"
            - "{{ system_tmp_dir }}/lazygit"
            - "{{ system_tmp_dir }}/README.md"
            - "{{ system_tmp_dir }}/LICENSE"

      when: not t_system_tools_lazygit_local_bin.stat.exists or (t_system_tools_lazygit_current_version is defined and t_system_tools_lazygit_current_version.stdout != system_tools_lazygit_version)

  when: want_system_tools_lazygit
